name: memory_card_game
description: A Flutter memory card game.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/card4.png
    - assets/images/card5.png
    - assets/images/card6.png
    - assets/images/card7.png
    - assets/images/card8.png
    - assets/sounds/Bossa Antigua.mp3
    - assets/sounds/Daily Beetle.mp3
    - assets/sounds/flipcard.wav
    - assets/sounds/match.wav
    